services:
  - type: web
    name: terratwin-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
